import { Schema, model }  from "mongoose";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

const userSchema = new Schema(
    // id will be automatically generated by mongoDB, which as the primary Key
    {
        username : {
            type: String,
            required:true,
            lowercase:true,
            trim:true,
            unique:true,
            index:true  // for effiecient seraching
        },
        email : {
            type: String,
            required:true,
            lowercase:true,
            unique:true,
            trim:true
        },
        fullName : {
            type: String,
            required : true,
            trim:true,
            index:true
        },
        avatar : {
            type : String,  // cloudinary URL
            required : true
        },
        coverImage : {
            type : String, // cloudinary URL
        },
        watchHistory : [
            {
                type: Schema.Types.ObjectId,
                ref:'Video'
            }
        ],
        password : {
            type : String,
            required:[true, 'Password is required'],
        },
        refreshToken : {
            type : String,
        }
    },
    {timestamps: true}
)

// use regular function for 'pre' as it need a reference - 'this'

userSchema.pre('save', async function(next){
    // bcrypt.hash(whatToHash, Salt/Rounds)
    if(!this.isModified('password')) return next();

    this.password = bcrypt.hash(this.password, 10);
    next();
})

// custom methods to validate password
userSchema.methods.isPasswordCorrect = async function(password){
    return await bcrypt.compare(password, this.password); // returns a true or false
}

// Generating Acess and Refresh tokens, this generation doesn't take much time, so need of async-await
userSchema.methods.generateAccessToken = function(){
    return jwt.sign(
        {
            _id : this._id,
            username : this.username,
            email : this.email,
            fullName : this.fullName 
        },
        process.env.ACCESS_TOKEN_SECRET,
        {
            expiresIn:ACCESS_TOKEN_EXPIRY
        }
    )
}

userSchema.methods.generateRefreshToken = function(){
    return jwt.sign(
        {
            _id : this._id,
        },
        process.env.REFRESH_TOKEN_SECRET,
        {
            expiresIn:REFRESH_TOKEN_EXPIRY
        }
    )
}

export default User = new model('User', userSchema);